version: '3'
services:
  webserver:
    container_name: webserver
    image: nginx:alpine
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    ports:
      - "8080:80"
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src:/var/www/html:cached
    working_dir: /var/www/html

  db:
    image: mysql:latest
    container_name: mysql
    ports:
      - "4306:3306"
    volumes:
      - ./docker/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: zpai_project
      MYSQL_ROOT_PASSWORD: secret

#  node:
#    image: node:14.18-alpine
#    container_name: npm
#    working_dir: /var/www/html
#    volumes:
#      - ./src:/var/www/html
#    entrypoint: ['npm']
